title: Lariicsa
email: dejamepienso@gmail.com
description: My web
twitter_username: lariicsa
github_username:  lariicsa

sass:
    sass_dir: _scss
    style: compressed

markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

gems:
  - octopress-autoprefixer
  - jekyll-watch


livereload: false
paginate: 3
paginate_path: "/blog/page:num/"